### ISSUE TITLE
Authorization fail when idntSwd has leading zeros

### ISSUE THREAD

**Issue by AwesomeGogo** [gilek/ewus#6]
Hello, after updating library to version 3, i cant login into EWUS because new Credentials param idntSwd is int or null, if I cast that string value into int with leading zeros, it cuts them down and the value is wrong. I think its the same for idntLek. I suggest to change that params to be string type.

**Comment by gilek** [comment]
Fixed. Thanks for reporting:) Since it was a braking change, I had to add the new 4.0.0 tag.
